### ISSUE TITLE
PFSS file not found

### ISSUE THREAD

**Issue by MohamedNedal** [Christian-Palmroos/sub_pfss_analysis_notebook#5]
Hello, I encountered this error white running the notebook `pfsspy_notebook` 
Where can I get the required input files, please? 

![image](https://user-images.githubusercontent.com/43330567/176700758-e6814556-19a0-4fd1-8768-265eb28007cb.png)

**Comment by Christian-Palmroos** [comment]
Hi! Did you get a confirmation to your email address from JSOC of your requested hmi map? Also, was your Carrington rotation a valid one?

Asking because I have not seen that exact TypeError in my notebook ever.

**Comment by MohamedNedal** [comment]
Hi @Christian-Palmroos  Sorry for the late reply! 
I didn't register with my email to JSOC. Can you please tell me how to do that?

**Comment by Christian-Palmroos** [comment]
Hello! You can register here:
http://jsoc.stanford.edu/ajax/register_email.html

**Comment by MohamedNedal** [comment]
Great! Thank you
